---
- name: Check if fish is already the default shell
  shell: echo $SHELL | grep -q fish
  register: fish_check
  failed_when: false
  changed_when: false

- name: Get fish shell path
  shell: which fish
  register: fish_path
  changed_when: false

- name: Set fish as default shell
  ansible.builtin.user:
    name: "{{ user }}"
    shell: "{{ fish_path.stdout }}"
  become: yes
  when: fish_check.rc != 0
