---
- name: Download chezmoi installer
  get_url:
    url: "{{ chezmoi_installer_url }}"
    dest: "/tmp/chezmoi-installer.sh"
    mode: '0755'

- name: Install chezmoi binary
  shell: |
    sh /tmp/chezmoi-installer.sh
  become_user: "{{ user }}"
  become: yes

- name: Initialize and apply chezmoi with local dotfiles
  shell: |
    ~/.local/bin/chezmoi init --apply --source "{{ dotfiles_dir }}"
  become_user: "{{ user }}"
  become: yes

- name: Clean up chezmoi installer
  file:
    path: "/tmp/chezmoi-installer.sh"
    state: absent
