---
oh_my_zsh_url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
oh_my_zsh_plugins_dir: "{{ home_dir }}/.oh-my-zsh/custom/plugins"
oh_my_zsh_themes_dir: "{{ home_dir }}/.oh-my-zsh/custom/themes"
