---
- name: Check if oh-my-zsh is already installed
  stat:
    path: "{{ home_dir }}/.oh-my-zsh/oh-my-zsh.sh"
  register: oh_my_zsh_stat

- name: Install oh-my-zsh
  shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended'
  environment:
    HOME: "{{ home_dir }}"
  when: not oh_my_zsh_stat.stat.exists

- name: Create oh-my-zsh custom plugins directory
  file:
    path: "{{ home_dir }}/.oh-my-zsh/custom/plugins"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0755"

- name: Install zsh-syntax-highlighting plugin
  git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    version: master
    update: yes

- name: Install zsh-autosuggestions plugin
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    version: master
    update: yes

- name: Install zsh-completions plugin
  git:
    repo: "https://github.com/zsh-users/zsh-completions.git"
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-completions"
    version: master
    update: yes
