# -*- mode: ruby -*-
# vi: set ft=ruby :

######################################################
# Ruby On Rails stack:
#   OS:
#     · Ubuntu Server 14.04 LTS (Trusty Tahr) 64 bits
#   Tools:
#     · Git
#     · Rbenv
#   Languages:
#     · Ruby 2.2.3
#     · Python 2.7.6 
#     · NodeJS
#   Gems:
#     · Bundler
#     · Rails
#   Database:
#     · MySQL
#
#   Notes: 
#     · Development server at 'localhost:3000'
#     · Default memory for the VM set to 1GB
#     · Make sure that you have also 'bootstrap.sh'
######################################################

Vagrant.configure(2) do |config|
  # Uses "ubuntu/trusty64" Ubuntu Server 14.04 LTS (Trusty Tahr) 64 bits
  # If you need 32 bits change this line by:
  #     config.vm.box = "ubuntu/trusty32"
  config.vm.box = "ubuntu/trusty64"

  # Forward the Rails server default port to the host.
  config.vm.network "forwarded_port", guest: 3000, host: 3000

  # Provider-specific configuration.
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM (set to 1GB):
    vb.memory = "1024"
  end
  
  # Enable provisioning with a shell script. Install dev stack.
  #config.vm.provision :shell, privileged: false, path: "bootstrap.sh"
end
